export const colors = {
  primary: '#F47C38',
  primaryDark: '#E06A20',
  primaryLight: '#FDE8DC',
  secondary: '#1A2C3E',
  secondaryLight: '#2D4A6E',
  background: '#F8FAFC',
  cardBg: '#FFFFFF',
  border: '#E2E8F0',
  text: '#1E293B',
  textLight: '#64748B',
  success: '#10B981',
  danger: '#EF4444',
  warning: '#F59E0B',
  purple: '#8B5CF6',
};

export const globalStyles = {
  container: {
    minHeight: '100vh',
    backgroundColor: colors.background,
    padding: '2rem',
  },
  card: {
    maxWidth: '1400px',
    margin: '0 auto',
    backgroundColor: colors.cardBg,
    borderRadius: '24px',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    padding: '2rem',
  },
  title: {
    fontSize: '1.875rem',
    fontWeight: '700',
    color: colors.secondary,
    marginBottom: '0.5rem',
  },
  subtitle: {
    fontSize: '0.875rem',
    color: colors.textLight,
  },
  btnPrimary: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.625rem 1.25rem',
    backgroundColor: colors.primary,
    color: 'white',
    border: 'none',
    borderRadius: '40px',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  btnSecondary: {
    padding: '0.625rem 1.25rem',
    backgroundColor: colors.background,
    color: colors.text,
    border: `1px solid ${colors.border}`,
    borderRadius: '12px',
    fontSize: '0.875rem',
    fontWeight: '500',
    cursor: 'pointer',
  },
  input: {
    padding: '0.625rem 0.875rem',
    border: `1px solid ${colors.border}`,
    borderRadius: '12px',
    fontSize: '0.875rem',
    width: '100%',
  },
  label: {
    fontSize: '0.75rem',
    fontWeight: '600',
    color: colors.text,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
};